# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: nft-marketplace-indexer
event_decoder: viem
output: generated
unordered_multichain_mode: true
preload_handlers: true
field_selection:
  transaction_fields:
    - hash

networks:
  - id: 1
    start_block: 0
    contracts:
      - name: Seaport
        address:
          - "0x0000000000000068F116a894984e2DB1123eB395" # Seaport 1.6
          - "0x00000000000000ADc04C56Bf30aC9d3c0aAF14dC" # Seaport 1.5
          - "0x00000000000001ad428e4906aE43D8F9852d0dD6" # Seaport 1.4
          - "0x0000000000000aD24e80fd803C6ac37206a45f15" # Seaport 1.3
          - "0x00000000000006c7676171937C444f6BDe3D6282" # Seaport 1.2
          - "0x00000000006c3852cbEf3e08E8dF289169EdE581" # Seaport 1.1
        handler: src/SeaportEventHandlers.ts
        events:
          - event: OrderFulfilled(bytes32 orderHash, address indexed offerer, address indexed zone, address recipient, (uint8,address,uint256,uint256)[] offer, (uint8,address,uint256,uint256,address)[] consideration)

      - name: SuperRareV1
        address:
          - "0x41a322b28d0ff354040e2cbc676f0320d8c8850d"
        handler: src/SuperRareV1EventHandlers.ts
        events:
          - event: Sold(address buyer, address seller, uint256 amount, uint256 tokenId)

      - name: SuperRareBazaar
        address:
          - "0x6D7c44773C52D396F43c2D511B81aa168E9a7a42"
        handler: src/SuperRareBazaarEventHandlers.ts
        events:
          - event: AcceptOffer(address indexed originContract, address indexed bidder, address indexed seller, address currencyAddress, uint256 amount, uint256 tokenId, address[] splitAddresses, uint8[] splitRatios)
          - event: Sold(address indexed originContract, address indexed buyer, address indexed seller, address currencyAddress, uint256 amount, uint256 tokenId)
          - event: AuctionSettled(address indexed contractAddress, address indexed bidder, address seller, uint256 indexed tokenId, address currencyAddress, uint256 amount)

      - name: SuperRareAuctionHouse
        address:
          - "0x8c9F364bf7a56Ed058fc63Ef81c6Cf09c833e656"
        handler: src/SuperRareAuctionHouseEventHandlers.ts
        events:
          - event: AuctionSettled(address indexed contractAddress, address indexed bidder, address seller, uint256 indexed tokenId, uint256 amount)

      - name: KnownOrigin
        address:
          - "0xf11ED77fD65840b64602526DDC38311E9923c81B"
        handler: src/KnownOriginEventHandlers.ts
        events:
          - event: BuyNowPurchased(uint256 indexed tokenId, address buyer, address currentOwner, uint256 price)
